echo "Let's install some extensions!"

code --install-extension apvarun.celestial
code --install-extension Babadzhanov.retro-vibes
code --install-extension Bhanu1776.jellyfish-retro
code --install-extension birdlinux.catppuccin-dark-theme
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dP-faces.dplanets-theme
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension ftsamoyed.theme-pink-cat-boo
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension guilhermerodz.omni-owl
code --install-extension hassancoder1.astral-bloom
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension jasonnutter.search-node-modules
code --install-extension JoelCrosby.one-dark-darker
code --install-extension LeonardSSH.vscord
code --install-extension MichaelMichaud.retro-doc
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.symbols
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension nicolasdschmidt.lunar-pink
code --install-extension orsenkucher.vscode-graphql
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension rocketseat.theme-omni
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension SonarSource.sonarlint-vscode
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-portuguese-brazilian
code --install-extension TabNine.tabnine-vscode
code --install-extension Tyriar.theme-sapphire
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WallabyJs.console-ninja