echo "Let's install some extensions!"

code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension apvarun.celestial
code --install-extension burkeholland.simple-react-snippets
code --install-extension chris-noring.node-snippets
code --install-extension christian-kohler.path-intellisense
code --install-extension clinyong.vscode-css-modules
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension dP-faces.dplanets-theme
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension ftsamoyed.theme-pink-cat-boo
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension icrawl.discord-vscode
code --install-extension jasonnutter.search-node-modules
code --install-extension JoelCrosby.one-dark-darker
code --install-extension kamikillerto.vscode-colorize
code --install-extension MichaelMichaud.retro-doc
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension mikestead.dotenv
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension msjsdiag.vscode-react-native
code --install-extension naumovs.color-highlight
code --install-extension nicolasdschmidt.lunar-pink
code --install-extension orsenkucher.vscode-graphql
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension Prisma.prisma
code --install-extension pyxel.min-darkest
code --install-extension redhat.fabric8-analytics
code --install-extension ritwickdey.LiveServer
code --install-extension rocketseat.theme-omni
code --install-extension Semgrep.semgrep
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension SonarSource.sonarlint-vscode
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-portuguese-brazilian
code --install-extension TabNine.tabnine-vscode
code --install-extension Tyriar.theme-sapphire
code --install-extension WallabyJs.console-ninja
code --install-extension whizkydee.material-palenight-theme
code --install-extension yhpnoraa.beauty
code --install-extension Zignd.html-css-class-completion